dateModified: 1725893986
email:
  fromEmail: ryan@craftquest.io
  fromName: 'House Quest'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4052097c-4aec-4442-af4c-df0a26b20065: 'House Quest' # House Quest
    d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: 'House Quest' # House Quest
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'House Quest'
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
