defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0640d26a-1d3a-4e0b-abec-b721bf92529a # Market News
handle: marketNews
maxAuthors: 1
name: 'Market News'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: market-news/_entry.twig
    uriFormat: 'market-news/{slug}'
type: channel
